import { NextPage } from "next";
import Head from "next/head";
import Main from "../components/Main";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full h-screen">
        <Sidebar />
        <Main />
        <Widgets />
      </main>
    </div>
  );
};

export default Home;
